language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.2.1"
    - jdk: oraclejdk8
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.2.1"
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "test:scalastyle"
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION package
after_success:
  - sbt coverageReport coveralls
